Migrate zipformer model to other Chinese datasets
k2-fsa/icefall pull request #1216
Opened 2023-08-14 03:55 UTC by JinZr

Provided datasets are listed below: 
1. aidatatng_200zh
2. aishell
3. aishell2
4. aishell4

2023-10-22 14:53 UTC, csukuangfj commented on egs/aishell/ASR/RESULTS.md
> +
Could you please upload pre-trained models to huggingface and post a link here?

2023-10-22 14:55 UTC, csukuangfj requested changes
Thanks! Left some minor comments about uploading pre-trained models to huggingface.

2023-10-22 14:55 UTC, csukuangfj commented on egs/aishell2/ASR/RESULTS.md
> +[./zipformer](./zipformer)
Could you upload the models to huggingface?

2023-10-22 14:55 UTC, csukuangfj commented on egs/aishell4/ASR/RESULTS.md
> +|------------------------|------|---------------------------------------|
Could you upload the models to huggingface?

2023-10-22 14:58 UTC, csukuangfj commented on egs/aidatatang_200zh/ASR/prepare.sh
> +perturb_speed=true
Could you update RESULTS.md for aidatatang_200zh about zipformer?

2023-10-24 08:03 UTC, csukuangfj reviewed
Thanks!

2023-10-24 08:09 UTC, JinZr commented on egs/aishell/ASR/README.md
> +Please refer to <https://icefall.readthedocs.io/en/latest/recipes/Non-streaming-ASR/aishell/index.html> for how to run models in this recipe.
the latest commit should fix this issue, thanks!

2023-10-24 08:23 UTC, csukuangfj approved these changes

2023-10-24 08:24 UTC, merged