[WIP] F5-TTS Training Recipe for WenetSpeech4TTS
k2-fsa/icefall pull request #1846
Opened 2024-12-24 07:39 UTC by yuekaizhang

Added Icefall style training codes based on https://github.com/SWivid/F5-TTS.

TODO:
- [ ] Code clean
- [ ] Update README.md
- [ ] Upload training results & logs

2024-12-24 07:43 UTC, yfyeung commented
Nice work

2025-01-21 04:52 UTC, JinZr commented
ok! I’ll look into it this weekend

Best Regards
Jin


Yuekai Zhang ***@***.***>于2025年1月20日 周一17:56写道：

> @yuekaizhang <https://github.com/yuekaizhang> requested your review on:
> #1846 <https://github.com/k2-fsa/icefall/pull/1846> [Ready] F5-TTS
> Training Recipe for WenetSpeech4TTS.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/k2-fsa/icefall/pull/1846#event-15996100744>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOON42DPXKMMFHAKGV2EE332LTB3DAVCNFSM6AAAAABUEJMCKCVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJVHE4TMMJQGA3TINA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2025-01-22 08:49 UTC, yfyeung commented on egs/wenetspeech4tts/TTS/f5-tts/vocab.txt
Could you provide instructions on how to generate this file? Thanks.

2025-01-26 08:41 UTC, JinZr requested changes

2025-01-26 08:41 UTC, JinZr commented on egs/wenetspeech4tts/TTS/prepare.sh
> +    # lhotse combine $pieces data/fbank/${prefix}_cuts_${subset}.jsonl.gz
the ''lhotse combine'' command is commented out, shouldn't this be executed after pieces are located to ensure proper integration?

2025-01-26 08:41 UTC, JinZr commented on egs/wenetspeech4tts/TTS/f5-tts/speech_synthesis.py
seems like this class provides the exact same functionality as the speech_synthesis dataset in lhotse, maybe we could try to use the lhotse built-in one to replace this

2025-01-26 08:43 UTC, JinZr commented
hi! i just finished reviewing this pr and it looks great!

i've left a few comments in it, please take a look when you have a moment

thank you!

2025-01-27 01:57 UTC, yuekaizhang commented on egs/wenetspeech4tts/TTS/prepare.sh
> +    # lhotse combine $pieces data/fbank/${prefix}_cuts_${subset}.jsonl.gz
Fixed.

2025-01-27 02:52 UTC, yuekaizhang commented on egs/wenetspeech4tts/TTS/f5-tts/speech_synthesis.py
The speech_synthesis class in Lhotse restricts the audio file to be specified and must exist.  See https://github.com/lhotse-speech/lhotse/blob/master/lhotse/dataset/speech_synthesis.py#L74

To use pre-extracted features from https://huggingface.co/datasets/yuekai/wenetspeech4tts_lhotse_manifest/tree/main/fbank without having to download the wav files (the former is only over 100 GB, while all wav files are nearly 1 TB), I used this custom file to comment out some unnecessary items, such as audio.

2025-01-27 02:55 UTC, yuekaizhang commented on egs/wenetspeech4tts/TTS/f5-tts/speech_synthesis.py
At the same time, in the future, there may be further expansion of the existing custom speech_synthesis file, such as adding the key speech_semantic tokens; this separate file would be more flexible.

2025-01-27 08:20 UTC, JinZr commented
i make a few commits to fix the flake8 and black formatting err, and i think this pr is good to go now.

2025-01-27 08:20 UTC, JinZr approved these changes

2025-01-27 08:33 UTC, merged